src/main/java/br/cesjf/hotellucena/controller/ApartamentoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.hotellucena.controller;

import br.cesjf.hotellucena.dao.ApartamentoDAO;
import br.cesjf.hotellucena.model.Apartamento;
import java.util.ArrayList;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

import com.lowagie.text.BadElementException;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import java.io.IOException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.FillPatternType;

/**
 *
 * @author tassio
 */
@ManagedBean(name = "apartamentosBean")
@ViewScoped
public class ApartamentoBean {

    Apartamento apartamento = new Apartamento();

    List apartamentos = new ArrayList();

    //construtor
    public ApartamentoBean() {
        apartamentos = new ApartamentoDAO().buscarTodas();
        apartamento = new Apartamento();
    }

    //Métodos dos botões 
    public void record(ActionEvent actionEvent) {
        new ApartamentoDAO().persistir(apartamento);
        apartamentos = new ApartamentoDAO().buscarTodas();
        apartamento = new Apartamento();
    }

    public void exclude(ActionEvent actionEvent) {
        new ApartamentoDAO().remover(apartamento);
        apartamentos = new ApartamentoDAO().buscarTodas();
        apartamento = new Apartamento();
    }

    //getters and setters
    public Apartamento getApartamento() {
        return apartamento;
    }

    public void setApartamento(Apartamento apartamento) {
        this.apartamento = apartamento;
    }

    public List getApartamentos() {
        return apartamentos;
    }

    public void setApartamentos(List apartamentos) {
        this.apartamentos = apartamentos;
    }

    public void postProcessXLS(Object document) {
        HSSFWorkbook wb = (HSSFWorkbook) document;
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow header = sheet.getRow(0);

        HSSFCellStyle cellStyle = wb.createCellStyle();
        cellStyle.setFillForegroundColor(HSSFColor.GREEN.index);
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        for (int i = 0; i < header.getPhysicalNumberOfCells(); i++) {
            HSSFCell cell = header.getCell(i);

            cell.setCellStyle(cellStyle);
        }
    }

    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);

        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        //String logo = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";

        // pdf.add(Image.getInstance(logo));
    }

}

src/main/java/br/cesjf/hotellucena/controller/CategoriaBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.hotellucena.controller;

import br.cesjf.hotellucena.dao.CategoriaDAO;
import br.cesjf.hotellucena.model.Categoria;
import java.util.ArrayList;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;

import com.lowagie.text.BadElementException;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import java.io.IOException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.FillPatternType;

/**
 *
 * @author tassio
 */
@ManagedBean(name = "categoriasBean")
@ViewScoped
public class CategoriaBean {

    Categoria categoria = new Categoria();

    List categorias = new ArrayList();

    //construtor
    public CategoriaBean() {
        categorias = new CategoriaDAO().buscarTodas();
        categoria = new Categoria();
    }

    //Métodos dos botões 
    public void record(ActionEvent actionEvent) {
        new CategoriaDAO().persistir(categoria);
        categorias = new CategoriaDAO().buscarTodas();
        categoria = new Categoria();
    }

    public void exclude(ActionEvent actionEvent) {
        new CategoriaDAO().remover(categoria);
        categorias = new CategoriaDAO().buscarTodas();
        categoria = new Categoria();
    }

    //getters and setters
    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public List getCategorias() {
        return categorias;
    }

    public void setCategorias(List categorias) {
        this.categorias = categorias;
    }

    public void postProcessXLS(Object document) {
        HSSFWorkbook wb = (HSSFWorkbook) document;
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow header = sheet.getRow(0);

        HSSFCellStyle cellStyle = wb.createCellStyle();
        cellStyle.setFillForegroundColor(HSSFColor.GREEN.index);
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        for (int i = 0; i < header.getPhysicalNumberOfCells(); i++) {
            HSSFCell cell = header.getCell(i);

            cell.setCellStyle(cellStyle);
        }
    }

    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);

        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        //String logo = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";

        // pdf.add(Image.getInstance(logo));
    }
}

src/main/java/br/cesjf/hotellucena/controller/ConsultaUsuariosBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.hotellucena.controller;

import br.cesjf.hotellucena.dao.UsuariosDAO;
import br.cesjf.hotellucena.model.Usuarios;
import java.util.ArrayList;

import com.lowagie.text.BadElementException;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import java.io.IOException;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.FillPatternType;

/**
 *
 * @author tassio
 */
@ManagedBean(name = "consultaUsuariosBean")
@SessionScoped
public class ConsultaUsuariosBean {

    Usuarios usuario = new Usuarios();

    List usuarios = new ArrayList();

    //construtor
    public ConsultaUsuariosBean() {
        usuarios = new UsuariosDAO().buscarTodas();
        usuario = new Usuarios();
    }

    //getters and setters
    public Usuarios getUsuarios() {
        return usuario;
    }

    public void setUsuarios(Usuarios usuario) {
        this.usuario = usuario;
    }

    public List getUsuarioss() {
        return usuarios;
    }

    public void setUsuarioss(List usuarios) {
        this.usuarios = usuarios;
    }

    public void postProcessXLS(Object document) {
        HSSFWorkbook wb = (HSSFWorkbook) document;
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow header = sheet.getRow(0);

        HSSFCellStyle cellStyle = wb.createCellStyle();
        cellStyle.setFillForegroundColor(HSSFColor.GREEN.index);
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        for (int i = 0; i < header.getPhysicalNumberOfCells(); i++) {
            HSSFCell cell = header.getCell(i);

            cell.setCellStyle(cellStyle);
        }
    }

    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);

        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        //String logo = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";

        // pdf.add(Image.getInstance(logo));
    }
}

src/main/java/br/cesjf/hotellucena/controller/ConsultasReservasBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.hotellucena.controller;

import br.cesjf.hotellucena.dao.ReservasDAO;
import br.cesjf.hotellucena.model.Reservas;
import java.util.ArrayList;
import javax.faces.event.ActionEvent;

import com.lowagie.text.BadElementException;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.PageSize;
import java.io.IOException;
import java.time.Duration;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.FillPatternType;

/**
 *
 * @author tassio
 */
@ManagedBean(name = "consultaReservasBean")
@SessionScoped
public class ConsultasReservasBean {

    Reservas reserva = new Reservas();

    List reservas = new ArrayList();

    //construtor
    public ConsultasReservasBean() {
        reservas = new ReservasDAO().buscarAtivos();
        reserva = new Reservas();
    }

    //Métodos dos botões 
    public void record(ActionEvent actionEvent) {
        Reservas r = new Reservas();
        Duration duracao = Duration.between(reserva.getDataEntrada().toInstant(), reserva.getDataSaida().toInstant());
        /*reservas = new ReservasDAO().buscarAtivos();
        for (Object ap : reservas) {
            Reservas res = (Reservas) ap;
            Duration resagenda = Duration.between(res.getDataEntrada().toInstant(), res.getDataSaida().toInstant());
            if (res.getApartamentocodigoApartamento().getIdApartamento().equals(reserva.getApartamentocodigoApartamento().getIdApartamento()) && duracao.equals(resagenda)) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro!", "Quarto inválida nesta data"));
            } else
         */
        if (!duracao.isNegative() && !duracao.isZero()) {
            Double valor = r.camaExtra(reserva);
            if (valor != 0.0) {
                reserva.setValorPago(valor);
                new ReservasDAO().persistir(reserva);
                reservas = new ReservasDAO().buscarAtivos();
                reserva = new Reservas();
            } else {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro!", "Quantidade de Hóspedes inválida"));
            }
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Erro!", "Data selecionada inválida"));
        }
        //}
    }

    public void exclude(ActionEvent actionEvent) {
        new ReservasDAO().remover(reserva);
        reservas = new ReservasDAO().buscarAtivos();
        reserva = new Reservas();
    }

    public void checkin(ActionEvent actionEvent) {
        new ReservasDAO().checkin(reserva.getCodigoReserva());
        reservas = new ReservasDAO().buscarAtivos();
        reserva = new Reservas();
    }

    public void checkout(ActionEvent actionEvent) {
        new ReservasDAO().checkout(reserva.getCodigoReserva());
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Check out", "Saída Concluída"));
        reservas = new ReservasDAO().buscarAtivos();
        reserva = new Reservas();
    }

    //getters and setters
    public Reservas getReservas() {
        return reserva;
    }

    public void setReservas(Reservas reserva) {
        this.reserva = reserva;
    }

    public List getReservass() {
        return reservas;
    }

    public void setReservass(List reservas) {
        this.reservas = reservas;
    }

    public void postProcessXLS(Object document) {
        HSSFWorkbook wb = (HSSFWorkbook) document;
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow header = sheet.getRow(0);

        HSSFCellStyle cellStyle = wb.createCellStyle();
        cellStyle.setFillForegroundColor(HSSFColor.GREEN.index);
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        for (int i = 0; i < header.getPhysicalNumberOfCells(); i++) {
            HSSFCell cell = header.getCell(i);

            cell.setCellStyle(cellStyle);
        }
    }

    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);

        ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
        //String logo = servletContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";

        // pdf.add(Image.getInstance(logo));
    }

    public List<Reservas> buscarReservasUsuario(int id) {
        reservas = (List) new ReservasDAO().buscarReservas(id);
        return reservas;
    }

    public List<Reservas> buscarReservasApartamento(int id) {
        reservas = (List) new ReservasDAO().buscarReservasApartamento(id);
        return reservas;
    }
        
}

src/main/java/br/cesjf/hotellucena/controller/RelatorioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.hotellucena.controller;

import br.cesjf.hotellucena.util.Relatorio;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.omnifaces.cdi.ViewScoped;
import javax.inject.Named;
/**
 *
 * @author dmeireles
 */
@Named
@ViewScoped
public class RelatorioBean implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private String relatorio;
    
    private Map<String, String> tipos;
    
    private List<Date> range;

    public RelatorioBean() {
        tipos = new HashMap<String, String>();
        tipos.put("Relatório de Quartos Reservados", "Relatorio02");
        tipos.put("Relatório de Quartos Ocupados", "Relatorio01");
        tipos.put("Relatório de Reservas Concluídas", "Relatorio03");
        
        range = new ArrayList<Date>();
    }

    public String getRelatorio() {
        return relatorio;
    }

    public void setRelatorio(String relatorio) {
        this.relatorio = relatorio;
    }

    public Map<String, String> getTipos() {
        return tipos;
    }

    public void setTipos(Map<String, String> tipos) {
        this.tipos = tipos;
    }
    
    public void gerarRelatorio() {
        Relatorio relatorio = new Relatorio();
        relatorio.getRelatorio(this.relatorio, null, null);
    }
    
    public void gerarRelatorioGerencial() {
        Relatorio relatorio = new Relatorio();
        relatorio.getRelatorio("RelatorioGerencial", range.get(0), range.get(1));
    }

    public List<Date> getRange() {
        return range;
    }

    public void setRange(List<Date> range) {
        this.range = range;
    }
    
}

src/main/webapp/consulta_quarto.xhtml
<ui:composition template="/WEB-INF/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h2 class="page-header">Consultar Quarto</h2>
        <br/>

        <h:form>
            <p:dataTable var="lista" value="#{apartamentosBean.apartamentos}"
                         id="tabelaAgent" emptyMessage="Nenhum registro encontrado"
                         paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                         paginator="true" rows="10" rowsPerPageTemplate="5,10,25,50,100,9999" style="width:100%">
                              
                <p:column headerText="Código" sortBy="#{lista.codigoApartamento}" filterBy="#{lista.codigoApartamento}">

                    <h:outputText value="#{lista.codigoApartamento}" />
                </p:column>
                <p:column headerText="Tipo" sortBy="#{lista.categoriacodigoCategoria.tipoCategoria}" filterBy="#{lista.categoriacodigoCategoria.tipoCategoria}">

                    <h:outputText value="#{lista.categoriacodigoCategoria.tipoCategoria}" />

                </p:column>
                <p:column>
                    <p:commandButton title="Details" 
                                     value="Details" 
                                     icon="ui-icon-zoomin" 
                                     action="/faces/relatorio_apartamento.xhtml?faces-redirect=true"
                                     ajax="true">
                        <f:setPropertyActionListener value="#{lista}" target="#{consultaApartamentosBean.apartamento}" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/reservas.xhtml
<ui:composition template="/WEB-INF/templates/layout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="content">
        <h2 class="page-header">Gerenciamento de Reservas</h2>
        <br/>
        <h:form id="formPrincipal">
            <p:messages id="messages" showDetail="true" closable="true" />
            <div align="center">
                <p:dataTable var="lista" value="#{reservasBean.reservass}"
                             id="tabelaActivity" emptyMessage="Nenhum registro encontrado"
                             paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                             paginator="true" rows="10" rowsPerPageTemplate="5,10,25,50,100,9999" style="width:100%">

                    <p:column headerText="Código" sortBy="#{lista.codigoReserva}" filterBy="#{lista.codigoReserva}">

                        <h:outputText value="#{lista.codigoReserva}" />

                    </p:column>

                    <p:column headerText="Cliente" sortBy="#{lista.usuarioscodUsuario.nomeUsuario}" filterBy="#{lista.usuarioscodUsuario.nomeUsuario}">

                        <h:outputText value="#{lista.usuarioscodUsuario.nomeUsuario}" />

                    </p:column>

                    <p:column headerText="Data Entrada" sortBy="#{lista.dataEntrada}" filterBy="#{lista.dataEntrada}">

                        <h:outputText value="#{lista.dataEntrada}" >
                            <f:convertDateTime pattern="dd/MM/yyyy" />
                        </h:outputText>

                    </p:column>

                    <p:column headerText="Data Saída" sortBy="#{lista.dataSaida}" filterBy="#{lista.dataSaida}">
                        <center>
                            <h:outputText value="#{lista.dataSaida}" >
                                <f:convertDateTime pattern="dd/MM/yyyy" />
                            </h:outputText>
                        </center>
                    </p:column>
                    <p:column headerText="Número de Hospedes" sortBy="#{lista.numeroHospedes}" filterBy="#{lista.numeroHospedes}">

                        <h:outputText value="#{lista.numeroHospedes}" />

                    </p:column>

                    <p:column headerText="Apartamento" sortBy="#{lista.apartamentocodigoApartamento.codigoApartamento}" filterBy="#{lista.apartamentocodigoApartamento.codigoApartamento}">

                        <h:outputText value="#{lista.apartamentocodigoApartamento.codigoApartamento}" />

                    </p:column>

                    <p:column headerText="Valor" sortBy="#{lista.valorPago}" filterBy="#{lista.valorPago}">

                        <h:outputText value="#{lista.camaExtra(lista)}" >
                            <f:convertNumber currencyCode="BRL" type="currency" />
                        </h:outputText>

                    </p:column>

                    <p:column headerText="Estatus" sortBy="#{lista.status}" filterBy="#{lista.status}">

                        <h:outputText value="#{lista.status}" />

                    </p:column>

                    <p:column headerText="Opções" exportable="false">
                        <center>
                            <p:commandButton icon="ui-icon-check" value="Confirmar Checkin" onclick="PF('checkin').show();"> 
                                <f:setPropertyActionListener target="#{reservasBean.reservas}"
                                                             value="#{lista}" />
                            </p:commandButton>

                            <p:commandButton title="Confirmar Checkout" 
                                             value="Confirmar Checkout" 
                                             icon="ui-icon-close" 
                                             action="/faces/relatorio_checkout.xhtml?faces-redirect=true"
                                             ajax="true">
                                <f:setPropertyActionListener value="#{lista}" target="#{consultaReservasBean.reservas}" />
                            </p:commandButton>


                            <p:commandButton icon="ui-icon-trash" value="Cancelar" onclick="PF('remove').show();"> 
                                <f:setPropertyActionListener target="#{reservasBean.reservas}"
                                                             value="#{lista}" />
                            </p:commandButton> 
                        </center>
                    </p:column>

                </p:dataTable>
            </div>
            <br/>
            <p:column>
                <p:commandButton icon="ui-icon-plus" value="Novo" onclick="PF('record').show();">  
                </p:commandButton> 
            </p:column>
            <div align="center">
                <h3>Exportar dados da página</h3>

                <h:commandLink id="excel">
                    <p:graphicImage name="./images/exports/excel.png" />
                    <p:dataExporter type="xls" target="tabelaActivity" fileName="activitys" postProcessor="#{reservasBean.postProcessXLS}" />
                </h:commandLink>

                <h:commandLink id="pdf">
                    <p:graphicImage name="./images/exports/pdf.png" />
                    <p:dataExporter type="pdf" target="tabelaActivity" fileName="activitys" preProcessor="#{reservasBean.preProcessPDF}" />
                </h:commandLink>


                <h:commandLink>
                    <p:graphicImage name="./images/exports/csv.png" width="24"/>
                    <p:dataExporter type="csv" target="tabelaActivity" fileName="activitys" />
                </h:commandLink>

                <h:commandLink>
                    <p:graphicImage  name="./images/exports/xml.png" width="24"/>
                    <p:dataExporter type="xml" target="tabelaActivity" fileName="activitys" />
                </h:commandLink>
            </div>

            <p:confirmDialog global="true">  
                <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />  
                <p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />  
            </p:confirmDialog>  


            <p:dialog header="Novo" widgetVar="record" modal="true">


                <p:panelGrid id="panelRecord" columns="2"> 
                    Cliente:
                    <p:selectOneMenu id="resp" value="#{reservasBean.reservas.usuarioscodUsuario}" converter="usuarioConverter">
                        <f:selectItem itemLabel="Selecione" itemValue="" />
                        <f:selectItems value="#{usuariosBean.usuarioss}" var="respname" itemLabel="#{respname.nomeUsuario}" itemValue="#{respname}" />
                    </p:selectOneMenu>
                    Data Entrada:
                    <p:calendar id="entrada" value="#{reservasBean.reservas.dataEntrada}" />
                    Data Saída:
                    <p:calendar id="saida" value="#{reservasBean.reservas.dataSaida}" />
                    Número de Hóspedes:
                    <p:inputText id="hosp" value="#{reservasBean.reservas.numeroHospedes}" />
                    Apartamento:
                    <p:selectOneMenu id="resp2" value="#{reservasBean.reservas.apartamentocodigoApartamento}" converter="apartamentoConverter">
                        <f:selectItem itemLabel="Selecione" itemValue="" />
                        <f:selectItems value="#{apartamentosBean.apartamentos}" var="respname" itemLabel="#{respname.codigoApartamento}" itemValue="#{respname}" />
                    </p:selectOneMenu>
                    Estatus:
                    <p:selectOneMenu id="resp3" value="#{reservasBean.reservas.status}">
                        <f:selectItem itemLabel="Selecione" itemValue="" />
                        <f:selectItem itemLabel="Reservado" itemValue="Reservado" />
                        <f:selectItem itemLabel="Ocupado" itemValue="Ocupado" />
                    </p:selectOneMenu>

                </p:panelGrid>

                <br/>
                <p:commandButton value="Salvar"  
                                 actionListener="#{reservasBean.record}" onclick="record.hide()" alt="Record"/> 
            </p:dialog>

            <p:dialog header="Delete" widgetVar="remove" modal="false"> 
                Você tem certeza?
                <p:commandButton value="Deletar"  
                                 actionListener="#{reservasBean.exclude}" onclick="remove.hide()" alt="Delete" /> 
            </p:dialog>

            <p:dialog header="Delete" widgetVar="checkin" modal="false"> 
                Confirmar Checkin?
                <p:commandButton value="Confirmar"  
                                 actionListener="#{reservasBean.checkin}" onclick="checkin.hide()" alt="checkin" /> 
            </p:dialog>
        </h:form>
    </ui:define>
</ui:composition>